apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: organizeme
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
      - job_name: backend
        metrics_path: /metrics
        static_configs:
          - targets: ['backend-service.organizeme.svc.cluster.local:5000']
      - job_name: frontend
        metrics_path: /metrics
        static_configs:
          - targets: ['frontend-service.organizeme.svc.cluster.local:3000']
