apiVersion: v1
kind: Secret
metadata:
  name: organizeme-secret
  namespace: organizeme
type: Opaque
stringData:
  DB_USER: admin
  DB_PASSWORD: securepassword
  JWT_SECRET: your_jwt_secret_key_here
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: securepassword
